---
settings:
  name: ONTAP What's New
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Descripción general de las funciones de ONTAP 9.9.1 de NetApp
    url: "/index.html"
    type: solution
    entries:
    - title: Mejoras de System Manager
      url: "/ontap991fo_system_manager_enhancements.html"
    - title: Mejoras DE SAN
      url: "/ontap991fo_san_enhancements.html"
    - title: Mejoras en la protección de datos
      url: "/ontap991fo_data_protection_enhancements.html"
    - title: Otras adiciones importantes
      url: "/ontap991fo_other_major_additions.html"
    - title: Recursos técnicos
      url: "/ontap991fo_technical_resources.html"
  - title: Descripción general de las funciones de ONTAP 9.8 de NetApp
    url: "/ontap98fo_netapp_ontap.html"
    type: solution
    entries:
    - title: Mejoras en la simplicidad
      url: "/ontap98fo_simplicity_enhancements.html"
    - title: Protocolos de datos
      url: "/ontap98fo_data_protocols.html"
    - title: Eficiencias del almacenamiento
      url: "/ontap98fo_storage_efficiencies.html"
    - title: Protección de datos
      url: "/ontap98fo_data_protection.html"
    - title: Virtualización de VMware
      url: "/ontap98fo_vmware_virtualization.html"
    - title: Recursos técnicos
      url: "/ontap98fo_technical_resources.html"
